### ISSUE TITLE
Sidebar status doesn't update

### ISSUE THREAD

**Issue by alnoob** [FunctionalCorrectness/VS-Code-Language-Server-for-Dafny#2]
Hey,

cool extension.
However my sidebar state never changes to 'Verified' or 'Not Verified'. It remains 'Verifying'.

**Comment by markusschaden** [comment]
Hey alnoob

Could you please send me the file to verify that behavior. 
Did you try it with a easy program?

Thanks
Markus

**Comment by alnoob** [comment]
Hey, 

I was testing with super simple programs.
Say
`method simpleAssertion() {
    assert 1 == 2;
}`

i just realized its a bit more complicated. Once i change 2 to 1 the "Problems" tab updates immediately and the squiggly lines disappear. Also 'Verifying' will change to 'Verified' at some point. However the time it takes is more than a minute often.

**Comment by markusschaden** [comment]
Thanks for the fast response.
This is a behavior which we haven't encountered yet. 
Could you please send me your operating system and which DafnyServer version you're using.

Can you verify the program verification with Dafny.exe directly. Just open a command prompt and execute `dafny.exe simpleassert.dfy` or `mono dafny.exe simpleassert.dfy`

**Comment by alnoob** [comment]
OS is Win10, i ran the command: C:\Users\\...\\.dafny\dafny\dafny .\simple.dfy

```
Dafny program verifier version 1.9.9.40418, Copyright (c) 2003-2017, Microsoft.

Dafny program verifier finished with 1 verified, 0 errors
Compiled assembly into simple.dll
```

**Comment by markusschaden** [comment]
Right know you're both clueless what the problem could be. 
We will contact you as soon as possible.
We'll have tomorrow a exercise session with some students. Maybe we'll see a similar problem which we really could look into what the problem is.

**Comment by alnoob** [comment]
Good job,
the issue seems to be resolved. Though i got to say that i haven't been using the editor too much the last couple of days. So im not a 100% percent sure atm. Anyways thanks for the rapid fix!

**Comment by markusschaden** [comment]
Nice to hear that our latest release solved your problem.
